### ISSUE TITLE
User groups table name is hardcoded with the prefix piwigo_

### ISSUE THREAD

**Issue by tcgoetz** [petitssuisses/piwigo-ShareAlbum#100]
https://github.com/petitssuisses/piwigo-ShareAlbum/blob/ce6afe298240078db374b54b237408293a306b0e/include/sharealbum_functions.inc.php#L347

Fatal error: Uncaught mysqli_sql_exception: Table 'piwigo.piwigo_user_group' doesn't exist in /app/www/public/include/dblayer/functions_mysqli.inc.php:132 Stack trace: #0 /app/www/public/include/dblayer/functions_mysqli.inc.php(132): mysqli->query() #1 /config/www/plugins/ShareAlbum/include/sharealbum_functions.inc.php(348): pwg_query() #2 /config/www/plugins/ShareAlbum/include/public_events.inc.php(70): sharealbum_is_poweruser() #3 /app/www/public/include/functions_plugins.inc.php(264): sharealbum_add_button() #4 /app/www/public/index.php(351): trigger_notify() #5 {main} thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 132

In my installation, I have no table prefix.

**Comment by RomainGiraud** [comment]
Hello, I had the same problem and fixed the issue in my PR #101.
