### ISSUE TITLE
Fatal error caused by missing column

### ISSUE THREAD

**Issue by mattsches** [petitssuisses/piwigo-ShareAlbum#82]
Piwigo version: 11.5.0
Plugin version: 11.8
PHP: 7.4.18

After upgrading to the latest versions of Piwigo and this plugin respectively, I'm getting a fatal error in the `Shared Albums` tab of the plugin configuration:
```
Warning:  [mysql error 1054] Unknown column 's.created_by' in 'field list'
SELECT s.id, s.cat as 'category', c.name as `album`, c.uppercats as `uppercats`, s.user_id, u.username as `user`, s.code as 'code', s.creation_date as `creation_date`, count(l.id) as `visits`, max(l.visit_d) as `last_visit`, s.created_by, uc.username as `shared_by`
	FROM sharealbum s
	LEFT JOIN sharealbum_log l
		ON s.cat = l.cat_id 
	LEFT JOIN categories c
		ON c.id = s.cat
	LEFT JOIN users u
		ON u.id = s.user_id
    LEFT JOIN users uc
    	ON s.created_by = uc.id
	GROUP BY s.id
	ORDER BY s.creation_date DESC in /var/www/…/httpdocs/include/dblayer/functions_mysqli.inc.php on line 864
```

```
Fatal error: Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/.../httpdocs/include/dblayer/functions_mysqli.inc.php:930 Stack trace: #0 /var/www/.../httpdocs/plugins/ShareAlbum/admin/albums.php(117): query2array() #1 /var/www/.../httpdocs/plugins/ShareAlbum/admin.php(30): include('/var/www/vhosts...') #2 /var/www/.../httpdocs/admin/plugin.php(53): include_once('/var/www/vhosts...') #3 /var/www/.../httpdocs/admin.php(298): include('/var/www/vhosts...') #4 {main} thrown in /var/www/.../httpdocs/include/dblayer/functions_mysqli.inc.php on line 930
```
Looks like some DB migration failed during the update? Can I fix this manually on the DB?

**Comment by petitssuisses** [comment]
Hi, yes, it seems the upgrade procedure still fails.
You can create the missing column with this query : 
ALTER TABLE sharealbum  ADD COLUMN created_by mediumint(8) NULL
